services:
  mysql:
    image: mysql:8.0
    container_name: videojuegos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: videojuegos_db
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: videojuegos-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/videojuegos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APP_JWT_SECRET: 4a0efa73ee27ab4b2ecaa6955ea9c0d33a72281eb78c4addc6a83238e53c6114
      JAVA_OPTS: -Duser.timezone=UTC
    ports:
      - "8080:8080"

volumes:
  mysql_data:
